# Generated by Django 5.2.18 on 2026-10-09 12:59

import apps.bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='district',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='examinee',
            field=models.CharField(choices=[('self', 'Myself'), ('other', 'Someone else')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='municipality',
            field=models.CharField(blank=True, max_length=80, verbose_name='city / municipality'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='passport_back',
            field=models.FileField(blank=True, upload_to=apps.bookings.models.passport_upload_path),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='passport_front',
            field=models.FileField(blank=True, upload_to=apps.bookings.models.passport_upload_path),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='province',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
