# Generated by Django 5.2.18 on 2026-10-09 14:53

import apps.bookings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingrequest_candidate_email_and_more'),
        ('catalog', '0003_testsession_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='change_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='change_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='change_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, help_text='For example: Myself, Son, Client', max_length=40)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=40)),
                ('district', models.CharField(blank=True, max_length=40)),
                ('municipality', models.CharField(blank=True, max_length=80)),
                ('passport_front', models.FileField(blank=True, upload_to=apps.bookings.models.passport_upload_path)),
                ('passport_back', models.FileField(blank=True, upload_to=apps.bookings.models.passport_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='bookings.candidate'),
        ),
        migrations.CreateModel(
            name='DateAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, help_text='regular or ukvi', max_length=10)),
                ('test_format', models.CharField(blank=True, choices=[('computer', 'Computer-delivered'), ('computer_wop', 'Computer-delivered with Writing on Paper')], max_length=20)),
                ('month', models.CharField(blank=True, help_text='YYYY-MM', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.city')),
                ('test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.testtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
