# Generated by Django 5.2.18 on 2026-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingrequest_change_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='assigned_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (about 9:00 am to 12:00 pm)'), ('afternoon', 'Afternoon (about 1:00 pm to 4:00 pm)')], max_length=10),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='assigned_venue',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
