# Generated by Django 5.2.18 on 2026-10-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_single_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('received', 'Request received'), ('confirmed', 'Booking confirmed'), ('cancelled', 'Request cancelled'), ('assigned', 'Session and venue assigned'), ('change_resolved', 'Change request handled'), ('remark', 'Message from our team')], max_length=20),
        ),
    ]
