# Generated by Django 5.2.18 on 2026-10-09 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_remark_kind'),
        ('catalog', '0004_alter_testsession_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='requested_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.testsession'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('received', 'Request received'), ('confirmed', 'Booking confirmed'), ('cancelled', 'Request cancelled'), ('assigned', 'Session and venue assigned'), ('change_resolved', 'Change request handled'), ('remark', 'Message from our team'), ('date_changed', 'Test date changed')], max_length=20),
        ),
    ]
