# Generated by Django 5.2.18 on 2026-10-10 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Shown as the page heading. Keep it under about 60 characters.', max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Web address part. Filled in from the title if empty. Changing it later breaks old links.', max_length=120, unique=True)),
                ('excerpt', models.CharField(help_text='One or two sentences for the list and Google description (aim for 120 to 155 characters).', max_length=300)),
                ('body', models.TextField(help_text="Plain text. Blank line = new paragraph. '## Heading' and '### Subheading' for sections, lines starting '- ' for bullets, '1. ' for numbered steps, '**bold**', and [link text](/ielts-test-dates) for links.")),
                ('author', models.CharField(default='bookyourielts.com team', max_length=80)),
                ('meta_title', models.CharField(blank=True, help_text='Optional. Google title if different from the heading (under 60 characters).', max_length=70)),
                ('is_published', models.BooleanField(default=False, help_text='Untick to keep it as a draft.')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Shown on the post. A future date keeps it hidden until then.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
