# Generated by Django 5.2.18 on 2026-10-09 12:16

import apps.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Identifier used by the website. Do not change.', unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(help_text="Plain text. Blank lines start a new paragraph; lines starting '- ' become bullets.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('general', 'General (home page)'), ('booking', 'Booking'), ('fees', 'Fees and refunds'), ('computer', 'IELTS on computer'), ('modules', 'Academic vs General Training')], db_index=True, default='general', max_length=20)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(help_text='Plain text. Blank lines start a new paragraph.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['page', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(help_text='Admin WhatsApp number with country code, digits only (e.g. 9779812345678).', max_length=20, validators=[apps.core.models._validate_whatsapp_number])),
                ('booking_message_template', models.TextField(default='Hi, my name is {full_name}. I want to book IELTS. Test: {test_type} ({format}), Date: {date}, City: {city}. Reference: {booking_ref}', help_text='Placeholders: {full_name} {test_type} {format} {date} {city} {booking_ref}')),
                ('inquiry_message_template', models.TextField(default="Hi, my name is {name}. I want to book IELTS but I can't see dates for {city}/{test_type}. Please let me know about upcoming dates.", help_text='Placeholders: {name} {city} {test_type} {format} {month}')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('office_address', models.CharField(blank=True, max_length=255)),
                ('low_seat_threshold', models.PositiveSmallIntegerField(default=5, help_text="Show 'Few seats left' when this many seats or fewer remain.", validators=[django.core.validators.MinValueValidator(1)])),
                ('announcement', models.CharField(blank=True, help_text='Banner shown at the top of the site. Leave empty to hide.', max_length=255)),
                ('footer_disclaimer', models.TextField(default='bookyourielts.com is an independent service. IELTS is jointly owned by the British Council, IDP IELTS and Cambridge University Press & Assessment. We are not affiliated with or endorsed by them.')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
