# Generated by Django 5.2.18 on 2026-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faq_copy_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='general_inquiry_message_template',
            field=models.TextField(default='Hi, my name is {name}. I have a question about IELTS booking. {message}', help_text='Used when an inquiry is a general question rather than a search for dates. Placeholders: {name} {message}'),
        ),
    ]
