# Generated by Django 5.2.18 on 2026-10-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_general_inquiry_message_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='general_inquiry_message_template',
            field=models.TextField(default='Hi, my name is {name}. I have a question about IELTS booking. {message}', help_text='Used for general questions (not date searches). Placeholders: {name} {message}'),
        ),
    ]
