# Generated by Django 5.2.18 on 2026-10-09 18:50

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_real_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(help_text='Admin WhatsApp number with country code, digits only (e.g. 9779860688212).', max_length=20, validators=[apps.core.models._validate_whatsapp_number]),
        ),
    ]
