"""Nepal's provinces and districts (7 provinces, 77 districts)."""

PROVINCES: dict[str, list[str]] = {
    "Koshi": [
        "Taplejung",
        "Panchthar",
        "Ilam",
        "Jhapa",
        "Morang",
        "Sunsari",
        "Dhankuta",
        "Terhathum",
        "Sankhuwasabha",
        "Bhojpur",
        "Khotang",
        "Solukhumbu",
        "Okhaldhunga",
        "Udayapur",
    ],
    "Madhesh": ["Saptari", "Siraha", "Dhanusha", "Mahottari", "Sarlahi", "Rautahat", "Bara", "Parsa"],
    "Bagmati": [
        "Sindhuli",
        "Ramechhap",
        "Dolakha",
        "Sindhupalchok",
        "Kavrepalanchok",
        "Lalitpur",
        "Bhaktapur",
        "Kathmandu",
        "Nuwakot",
        "Rasuwa",
        "Dhading",
        "Makwanpur",
        "Chitwan",
    ],
    "Gandaki": [
        "Gorkha",
        "Lamjung",
        "Tanahun",
        "Syangja",
        "Kaski",
        "Manang",
        "Mustang",
        "Myagdi",
        "Parbat",
        "Baglung",
        "Nawalpur",
    ],
    "Lumbini": [
        "Parasi",
        "Rupandehi",
        "Kapilvastu",
        "Arghakhanchi",
        "Gulmi",
        "Palpa",
        "Dang",
        "Pyuthan",
        "Rolpa",
        "Eastern Rukum",
        "Banke",
        "Bardiya",
    ],
    "Karnali": [
        "Western Rukum",
        "Salyan",
        "Dolpa",
        "Humla",
        "Jumla",
        "Kalikot",
        "Mugu",
        "Surkhet",
        "Dailekh",
        "Jajarkot",
    ],
    "Sudurpashchim": [
        "Kailali",
        "Achham",
        "Doti",
        "Bajhang",
        "Bajura",
        "Kanchanpur",
        "Dadeldhura",
        "Baitadi",
        "Darchula",
    ],
}

DISTRICTS = {d for ds in PROVINCES.values() for d in ds}
