# Generated by Django 5.2.18 on 2026-10-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('intro', models.TextField(blank=True, help_text="Short paragraph shown on this city's IELTS dates page (helps Google). Plain text.")),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable identifier, e.g. academic. Used in URLs and filters.', unique=True)),
                ('name', models.CharField(max_length=80)),
                ('is_ukvi', models.BooleanField(default=False, help_text='UKVI tests cannot be taken with Writing on Paper.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='catalog.city')),
            ],
            options={
                'ordering': ['city__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('slot', models.CharField(choices=[('morning', 'Morning (about 9:00 am to 12:00 pm)'), ('afternoon', 'Afternoon (about 1:00 pm to 4:00 pm)')], default='morning', max_length=10)),
                ('format', models.CharField(choices=[('computer', 'Computer-delivered'), ('computer_wop', 'Computer-delivered with Writing on Paper')], default='computer', max_length=20)),
                ('fee_npr', models.PositiveIntegerField(verbose_name='fee (NPR)')),
                ('seats_total', models.PositiveIntegerField(default=0)),
                ('seats_booked', models.PositiveIntegerField(default=0, help_text='Updated automatically when bookings are confirmed.')),
                ('registration_closes_on', models.DateField(blank=True, help_text='Last day to register. Left empty = 6 days before the test.', null=True)),
                ('results_date', models.DateField(blank=True, help_text='Left empty = 5 days after (computer) or 13 days after (writing on paper).', null=True)),
                ('speaking_note', models.CharField(blank=True, help_text='e.g. Speaking test is on a separate slot, within 7 days before or after this date.', max_length=255)),
                ('is_visible', models.BooleanField(default=True, help_text='Untick to hide from students.')),
                ('notes', models.TextField(blank=True, help_text='Internal notes, never shown to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.city')),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.testtype')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.venue')),
            ],
            options={
                'ordering': ['date', 'slot', 'city__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_venue_per_city'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['date', 'city'], name='session_date_city_idx'),
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['is_visible', 'date'], name='session_visible_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='testsession',
            constraint=models.CheckConstraint(condition=models.Q(('seats_booked__lte', models.F('seats_total'))), name='seats_booked_lte_total'),
        ),
    ]
