# Generated by Django 5.2.18 on 2026-10-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='provider',
            field=models.CharField(choices=[('british_council', 'British Council'), ('idp', 'IDP')], default='british_council', help_text='The organisation that runs this test session.', max_length=20),
        ),
    ]
