# Generated by Django 5.2.18 on 2026-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_testsession_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (about 9:00 am to 12:00 pm)'), ('afternoon', 'Afternoon (about 1:00 pm to 4:00 pm)')], default='', help_text='Usually left empty. Morning or afternoon is assigned to each booking after it is made.', max_length=10),
        ),
    ]
