# Generated by Django 5.2.18 on 2026-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Send booking updates by email as well as in the portal.'),
        ),
    ]
