import type { Metadata } from "next";
import { BRAND_SUFFIX, DEFAULT_OG_ALT } from "./seo-config";
import type { Faq, TestSession } from "./types";

export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL ?? "https://bookyourielts.com").replace(
  /\/$/,
  "",
);
export const SITE_NAME = "bookyourielts.com";

// Generated by app/opengraph-image.tsx and app/twitter-image.tsx. Page-level openGraph replaces
// the inherited one, so the image is set explicitly here.
const OG_IMAGE = "/opengraph-image";
const TWITTER_IMAGE = "/twitter-image";

const MAX_TITLE = 60;

/** Adds the short brand only when the title does not already carry it and the result still fits. */
export function withBrand(title: string): string {
  const suffix = ` | ${BRAND_SUFFIX}`;
  if (title.toLowerCase().includes(BRAND_SUFFIX.toLowerCase())) return title;
  return title.length + suffix.length <= MAX_TITLE ? `${title}${suffix}` : title;
}

/**
 * Metadata for a page. One brand suffix at most, added only if it fits in about 60 characters.
 * `noindex` keeps the page out of search but lets crawlers follow its links.
 */
export function pageMetadata(opts: {
  title: string;
  description: string;
  path: string;
  noindex?: boolean;
}): Metadata {
  const url = `${SITE_URL}${opts.path}`;
  const title = withBrand(opts.title);
  return {
    title: { absolute: title },
    description: opts.description,
    alternates: { canonical: url },
    robots: opts.noindex ? { index: false, follow: true } : undefined,
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      title,
      description: opts.description,
      url,
      locale: "en_NP",
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: DEFAULT_OG_ALT }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: opts.description,
      images: [{ url: TWITTER_IMAGE, alt: DEFAULT_OG_ALT }],
    },
  };
}

export const organizationLd = (contactEmail?: string, phone?: string) => ({
  "@context": "https://schema.org",
  "@type": "Organization",
  name: SITE_NAME,
  url: SITE_URL,
  logo: `${SITE_URL}/static/logo.png`,
  description: "Independent IELTS booking assistance for students in Nepal.",
  areaServed: { "@type": "Country", name: "Nepal" },
  ...(contactEmail || phone
    ? {
        contactPoint: {
          "@type": "ContactPoint",
          contactType: "customer support",
          availableLanguage: ["English", "Nepali"],
          ...(contactEmail ? { email: contactEmail } : {}),
          ...(phone ? { telephone: phone } : {}),
        },
      }
    : {}),
});

export const faqLd = (faqs: Pick<Faq, "question" | "answer">[]) => ({
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.question,
    acceptedAnswer: { "@type": "Answer", text: f.answer.replace(/\n+/g, " ") },
  })),
});

export const breadcrumbLd = (items: { name: string; path: string }[]) => ({
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: items.map((it, i) => ({
    "@type": "ListItem",
    position: i + 1,
    name: it.name,
    item: `${SITE_URL}${it.path}`,
  })),
});

export const websiteLd = () => ({
  "@context": "https://schema.org",
  "@type": "WebSite",
  name: SITE_NAME,
  url: SITE_URL,
  inLanguage: "en",
});

/** WebPage with a data-driven dateModified, for the freshness-sensitive pages. */
export const webPageLd = (opts: { path: string; name: string; dateModified?: string | null }) => ({
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: opts.name,
  url: `${SITE_URL}${opts.path}`,
  inLanguage: "en",
  ...(opts.dateModified ? { dateModified: opts.dateModified } : {}),
});

/**
 * One ItemList of Event objects, one per open session. Dates only (times are confirmed after
 * booking), city-level location (no street address or venue unless the data has one), and the raw
 * numeric fee. `pageUrl` is the public page that lists the sessions.
 */
export const eventsLd = (sessions: TestSession[], pageUrl: string) => ({
  "@context": "https://schema.org",
  "@type": "ItemList",
  itemListElement: sessions.map((s, i) => ({
    "@type": "ListItem",
    position: i + 1,
    item: {
      "@type": "Event",
      name: `${s.test_type.name} (${s.format_label.toLowerCase()}), ${s.city.name}`,
      startDate: s.date,
      eventStatus: "https://schema.org/EventScheduled",
      eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
      location: {
        "@type": "Place",
        name: s.venue?.name ?? s.city.name,
        address: {
          "@type": "PostalAddress",
          ...(s.venue?.address ? { streetAddress: s.venue.address } : {}),
          addressLocality: s.city.name,
          addressCountry: "NP",
        },
      },
      organizer: { "@type": "Organization", name: s.provider_label },
      offers: {
        "@type": "Offer",
        price: s.fee_npr,
        priceCurrency: "NPR",
        url: pageUrl,
        availability: s.is_bookable ? "https://schema.org/InStock" : "https://schema.org/SoldOut",
        validThrough: s.registration_closes_on,
      },
    },
  })),
});
